## Working with NumPy

### Task 1:
    -- Import the numpy library and check its version.

In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.24.3


### Creating a NumPy Array:
    -NumPy arrays are a powerful way to store and process large datasets. In this section, you will learn to create arrays.

### Task 2:
       -- Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].
       -- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.
       -- Generate an array of 10 evenly spaced values between 0 and 5.

-- Create a 1D NumPy array from a Python list of numbers: [1, 2, 3, 4, 5].

In [30]:
# Creating a 1D NumPy array from apython list of numbers

arr1= np.array([1, 2, 3, 4, 5])
print("print the array 1: ",arr1)
print("Dimension of an array is: ",arr1.ndim)  # Findng the dimension of array
print("Shape of an array is: " , arr1.shape) # Finding the shape of an array

print the array 1:  [1 2 3 4 5]
Dimension of an array is:  1
Shape of an array is:  (5,)


In [51]:
# Creating a 2D NumPy array from apython list of numbers

arr2= np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
print("print the array 2: \n\n ",arr2)
print("\nDimension of an array is: ",arr1.ndim)  # Findng the dimension of array
print("Shape of an array is: " , arr1.shape) # Finding the shape of an array

print the array 2: 

  [[1 2 3 4 5]
 [1 2 3 4 5]]

Dimension of an array is:  1
Shape of an array is:  (5,)


 ### -- Create a 2D NumPy array of shape (3x3) using the numbers from 1 to 9.

In [48]:
arr3= np.random.randint(1,9,(3,3))
print("The below array is 2D Numpy array of shape(3x3) of number randomly generated from 1 to 9 \n")
print(arr3)

The below array is 2D Numpy array of shape(3x3) of number randomly generated from 1 to 9 

[[4 6 7]
 [2 1 1]
 [7 4 7]]


### -- Generate an array of 10 evenly spaced values between 0 and 5.

In [47]:
arr4= np.linspace(start= 0, stop= 5, num=10)
print("Array of 10 evenly spaced values between 0 and 5: \n")
print(arr4)

Array of 10 evenly spaced values between 0 and 5: 

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


### Indexing and Slicing Arrays:
    -Indexing and slicing allow you to access and modify specific elements of an array.

**Task 3:**

    Access the element in the second row, third column of the 2D array you created above.
    Slice the first two rows and the first two columns from the same array.
    Modify the value in the last row and first column to 100.

In [75]:
# Here the 2D array that we have created above is : arr3= np.random.randint(1,9,(3,3))
print(" Print the 2D Array that we have created above: \n", arr3)

#Accessing element using indexing

print(" Accessing the element is second row, third column arr3[1][2]: ", arr3[1][2])

#Accessing elemets using slicing
# array[<row_slice>,<col_slice>]
print("\n Slice the first two rows and the first two columns from the same array: \n", arr3[0:2,0:2])


#Modify the value in the last row and first column to 100.
arr3[2][0]=100
print("\n Modify the value in the last row and first column to 100.: \n", arr3 )



 Print the 2D Array that we have created above: 
 [[  4   6   7]
 [  2   1   1]
 [100   4   7]]
 Accessing the element is second row, third column arr3[1][2]:  1

 Slice the first two rows and the first two columns from the same array: 
 [[4 6]
 [2 1]]

 Modify the value in the last row and first column to 100.: 
 [[  4   6   7]
 [  2   1   1]
 [100   4   7]]


In [66]:
arr3[2][0]=100
arr3

array([[  4,   6,   7],
       [  2,   1,   1],
       [100,   4,   7]])

### Properties and Methods of NumPy Arrays
NumPy arrays have several useful properties and methods.

**Task 4:**

    Find the shape, size, and data type of the 2D array.
    Change the 1D array into a 2D array of shape (5,1).
    Flatten a multi-dimensional array back into a 1D array.

In [82]:
# Fiind the shape, size, and data type of the 2D array.
print("Print the 2D array created above:\n ", arr3)
print("Shape of an array:" ,arr3.shape)
print("size of an array:" ,arr3.size)
print("data tyoe of an array:" ,arr3.dtype)

Print the 2D array created above:
  [[  4   6   7]
 [  2   1   1]
 [100   4   7]]
Shape of an array: (3, 3)
size of an array: 9
data tyoe of an array: int32


In [98]:
#Change the 1D array into a 2D array of shape (5,1)
print("Array of 1D Created above: ", arr1)

#reshaping the given array into 2D array
array1= arr1.reshape(5,1)
print("2D ARray Created  by reshaping the arr1 above:\n",array1)

#Flatten a multi-dimensional array back into a 1D array.
# flatten() is somewhat same as ravel  but ravel is best for memory consumption
print("Flatten a multi-dimensional array back into a 1D array:\n",arr3.flatten() )


Array of 1D Created above:  [1 2 3 4 5]
2D ARray Created  by reshaping the arr1 above:
 [[1]
 [2]
 [3]
 [4]
 [5]]
Flatten a multi-dimensional array back into a 1D array:
 [  4   6   7   2   1   1 100   4   7]


## Operations on NumPy Arrays
    Perform operations such as addition, subtraction, multiplication, and matrix multiplication on arrays.

**Task 5:**

    Add 5 to every element in the 1D array.
    Multiply the 2D array by 3.
    Perform matrix multiplication between the following two arrays:
        A = np.array([[1, 2], [3, 4]])
        B = np.array([[5, 6], [7, 8]])

In [119]:
print("Lets see the 1D array that we have:\n", arr1)
print("Adding the value 5 to each element of array:")
print(np.add(5,arr1))

print("Multiplying the 2D array by 3:\n")
print(np.multiply(3,arr3))

#Perform matrix multiplication between the following two arrays:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print("Array of A\n", A)
print("Array of B\n", B)
print(f"Multiplication of A and B is: \n {np.dot(A,B)}")
print(f"Alternatively you can do Matix Multiplication of A and B using: A@B \n {A@B}")


Lets see the 1D array that we have:
 [1 2 3 4 5]
Adding the value 5 to each element of array:
[ 6  7  8  9 10]
Multiplying the 2D array by 3:

[[ 12  18  21]
 [  6   3   3]
 [300  12  21]]
Array of A
 [[1 2]
 [3 4]]
Array of B
 [[5 6]
 [7 8]]
Multiplication of A and B is: 
 [[19 22]
 [43 50]]
Alternatively you can do Matix Multiplication of A and B using: A@B 
 [[19 22]
 [43 50]]


### Understanding Broadcasting
**Broadcasting allows NumPy to work with arrays of different shapes during arithmetic operations.**

**Task 6:**

    Create a 3x3 matrix of ones and a 1D array of length 3.
    Add the 1D array to each row of the matrix using broadcasting.

In [150]:
#Create a 3x3 matrix of ones and a 1D array of length 3.
array_ones= np.ones(shape= (3,3))
print("3X3 Matrics of ones is:\n", array_ones)
array1= np.random.randint(0,10,3)
# array_1= np.array([1,2,3])
print("1D array of length 3\n ",array1)
# print("1D array of length 3\n"array_1)

#Add the 1D array to each row of the matrix using broadcasting.
result= array_ones+array1
print("Addition of 1D array to the Ma"result)

3X3 Matrics of ones is:
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1D array of length 3
  [1 1 0]


[[5. 6. 4.]
 [5. 6. 4.]
 [5. 6. 4.]]
